### ISSUE TITLE
microtemplate@^1.0.2 依赖包不存在？

### ISSUE THREAD

**Issue by zhouyec** [macacajs/macaca-reporter#22]
![image](https://user-images.githubusercontent.com/46813269/216502680-3b321dcf-100b-4cba-91ba-0f39ec645bd3.png)
microtemplate@^1.0.2 依赖应该怎么安装

**Comment by xudafeng** [comment]
https://github.com/macacajs/macaca-reporter/pull/23/files

**Comment by xudafeng** [comment]
@zhouyec 请升级 1.9.13
