### ISSUE TITLE
优化显示

### ISSUE THREAD

**Issue by xudafeng** [macacajs/macaca-reporter#3]
- [x] d3 image 太小
- [x] 有torchjs异常请求

**Comment by SamuelZhaoY** [comment]
<img width="1275" alt="screen shot 2017-11-19 at 5 50 02 pm" src="https://user-images.githubusercontent.com/8198256/32989506-862af9f6-cd52-11e7-9653-b886b293d74a.png">
graph 显示 貌似只支持到两层， 另外graph 显示需要优化一下, 目前的排版占用了太多space

**Comment by xudafeng** [comment]
https://github.com/macacajs/macaca-reporter/issues/6
