### ISSUE TITLE
Enhance the judgment of the ci environment

### ISSUE THREAD

**Issue by xudafeng** [macacajs/macaca-reporter#40]
CI environment does not need to delete temporary files https://github.com/macacajs/macaca-reporter/blob/master/lib/coverage.js#L69-L71

**Comment by xudafeng** [comment]
refer to the implementation of node

https://github.com/nodejs/node/blob/master/lib/internal/tty.js#L99-L101

**Comment by paradite** [comment]
https://github.com/watson/ci-info/blob/master/index.js
use this one?
