### ISSUE TITLE
建议增加国际化功能,方便浏览

### ISSUE THREAD

**Issue by freelyshadow** [macacajs/macaca-reporter#59]
实际使用过程中多数人对中文更为熟悉,建议能增加报告国际化功能

**Comment by zivyangll** [comment]
@freelyshadow 具体是哪些地方了？reporter 本身描述的文字不多，大多是英文的。

**Comment by freelyshadow** [comment]
就是报告上的关键词,支持国际化可能体验更好些

**Comment by zivyangll** [comment]
@freelyshadow 你看到的是测试用例的描述吧？reporter 代码里几乎没有中文的。

**Comment by zivyangll** [comment]
@freelyshadow 理解你的意思了，是要添加中文是吧？界面目前只有几个简单的英文单词，没有计划翻译为中文。
