### ISSUE TITLE
能否增加对于report输出路径配置的支持

### ISSUE THREAD

**Issue by albert-cai** [macacajs/macaca-reporter#64]

**Comment by zivyangll** [comment]
可以的，支持后同步。

**Comment by amosnothing** [comment]
???? 支持没有啊 老铁们！！！！如果没时间搞的话 我来帮你们写 ？？

**Comment by zivyangll** [comment]
@amosnothing 现阶段是支持的，ReadMe 中有写：

Support custom JSON file name by ths config:

mocha.opts:

--reporter macaca-reporter
--reporter-options reportJSONFilename=customReportJSONFilename
with command:

$ mocha test.js --reporter macaca-reporter --reporter-options reportJSONFilename=customReportJSONFilename
custom reporter directory with environment variable

MACACA_REPORTER_DIR=customDirName

**Comment by amosnothing** [comment]
这种用法实际上有点不合理，你这些配置我也有看过。但是我的场景是：多线程来触发报告生成，也就是需要每个线程执行完成之后生成的报告目录不一样，如果写在环境变量里面，依然没能解决我的问题。

**Comment by amosnothing** [comment]
我现在的做法是，执行的时候
1. 把测试用例移动到一个临时目录（并且每次都不同），因为报告里面的失败截图路径是根据用例的路径来生成的
2. 在 --Reporter-options 里面添加一个 reportHTMLFileName = html 文件名(我用的 uuid)
3. 在 lib/render.js 里，第 40 行新增代码 `  const reportHTMLFilename = opts.reporterOptions && opts.reporterOptions.reportHTMLFilename || 'index';
  options.fileName = reportHTMLFilename + '.html';`
4. 每次执行命令的时候都带上这个html 文件后缀
