### ISSUE TITLE
3.x  macaca-report 怎么生成自定义的 报告名称？

### ISSUE THREAD

**Issue by lrhcyh** [macacajs/macaca-reporter#66]
2.X 使用--reporter mochawesome-uirecorder  可以自定义报告的名称 reportName=xxx.html

3.x 怎么自定义？

**Comment by zivyangll** [comment]
macaca-reporter 支持自定义 json 文件名输出：
```bash
$ mocha test.js --reporter macaca-reporter --reporter-options reportJSONFilename=customReportJSONFilename
```

暂还不支持 index.html 修改，有很多依赖会直接用到。
