### ISSUE TITLE
请问一下为何 github 的版本和 npm 的版本不一致呢？

### ISSUE THREAD

**Issue by amosnothing** [macacajs/macaca-reporter#75]
github 的版本是1.3.29
npm的版本是 1.3.33

**Comment by zivyangll** [comment]
@amosnothing 都是 33 版本

https://www.npmjs.com/package/macaca-reporter
https://github.com/macacajs/macaca-reporter/blob/master/package.json

![image](https://user-images.githubusercontent.com/11460601/117911074-b192c780-b30f-11eb-8035-5aa1a9a8d7f6.png)

![image](https://user-images.githubusercontent.com/11460601/117911086-b9eb0280-b30f-11eb-931f-1e4b63a0459f.png)

![image](https://user-images.githubusercontent.com/11460601/117911104-c1121080-b30f-11eb-8df8-f9d53e6f3a93.png)

**Comment by amosnothing** [comment]
v1.3.29
@zivyangll zivyangll released this on 24 Sep 2020

不好意思没有表达清楚，上面发的这个是 github 上面的版本信息。
