### ISSUE TITLE
依赖没装？

### ISSUE THREAD

**Issue by jtyjty99999** [macacajs/macaca-reporter#8]
![image](https://user-images.githubusercontent.com/893152/29707633-81e43282-89b8-11e7-9b42-288789870290.png)
![image](https://user-images.githubusercontent.com/893152/29707671-9d8df16c-89b8-11e7-812c-323be71b8540.png)

**Comment by xudafeng** [comment]
https://github.com/macacajs/macaca-reporter/commit/d3040a65e296ee3de6d6457be24e8380a568e116

**Comment by xudafeng** [comment]
@jtyjty99999 已fix
